from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class ActionDetail(BaseModel):
    action_type: str = Field(..., description="Type of micro-action e.g. pre_cool, delay_start, soft_ramp")
    target_equipment: Optional[str] = Field(None, description="Equipment ID if applicable e.g. eq_comp_1")
    target_zone: Optional[str] = Field(None, description="Zone ID if applicable e.g. z_hvac_3")
    delay_minutes: Optional[int] = Field(None, description="Delay duration in minutes")
    temp_delta_celsius: Optional[float] = Field(None, description="Temperature adjustment in Celsius")
    ramp_cap_pct: Optional[float] = Field(None, description="Capacity percentage during ramp window")
    time_window: Optional[str] = Field(None, description="Operational time window")

class RecommendationObject(BaseModel):
    id: str = Field(..., description="Unique recommendation ID e.g. rec_042")
    type: Literal["composite", "sequence", "shift", "solar_advisory"] = Field(
        ..., description="Recommendation type, supporting composite multi-action schedules"
    )
    target: List[str] = Field(..., description="Target zone or equipment IDs")
    actions: List[ActionDetail] = Field(default_factory=list, description="List of sub-actions for composite schedules")
    estimated_savings_inr: float = Field(..., description="Estimated cost savings in INR")
    spike_risk_reduction_pct: float = Field(..., description="Percentage reduction in demand spike risk")
    baseline_peak_kw: float = Field(..., description="Baseline 15-min peak demand before optimization")
    optimized_peak_kw: float = Field(..., description="Optimized 15-min peak demand after load staggering")
    reasoning: str = Field(..., description="Natural language reasoning generated by explainer agent")
    cited_rule: str = Field(..., description="Identifier of DISCOM rule or threshold cited")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Agent confidence score (0.0 to 1.0)")
    requires_approval: bool = Field(True, description="Human approval gate flag")
    status: Literal["proposed", "approved", "rejected", "executed"] = Field("proposed", description="Approval status")
